#!/bin/bash
# Guide rapide pour démarrer Airflow manuellement

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     🚀 Guide de démarrage Airflow - CarPricePredictor        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Airflow est installé et configuré!"
echo "✅ DAG 'car_price_predictor_pipeline' détecté"
echo ""
echo "📋 Pour démarrer Airflow:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 MODE STANDALONE (Recommandé - Tout-en-un)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd $(pwd)"
echo "source .venv/bin/activate"
echo "export AIRFLOW_HOME=\$(pwd)/airflow"
echo "airflow standalone"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  ALTERNATIVE - Scheduler seul (sans interface web)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd $(pwd)"
echo "source .venv/bin/activate"
echo "export AIRFLOW_HOME=\$(pwd)/airflow"
echo "airflow scheduler"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  📊 Interface Web: http://localhost:8080                      ║"
echo "║  👤 Login: Voir les identifiants dans le terminal standalone ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "💡 Commandes utiles:"
echo ""
echo "  # Lister les DAGs"
echo "  export AIRFLOW_HOME=\$(pwd)/airflow && airflow dags list"
echo ""
echo "  # Tester le pipeline manuellement"
echo "  export AIRFLOW_HOME=\$(pwd)/airflow && airflow dags test car_price_predictor_pipeline 2026-02-14"
echo ""
echo "  # Activer le DAG (exécution automatique hebdomadaire)"
echo "  export AIRFLOW_HOME=\$(pwd)/airflow && airflow dags unpause car_price_predictor_pipeline"
echo ""
echo "  # Déclencher manuellement"
echo "  export AIRFLOW_HOME=\$(pwd)/airflow && airflow dags trigger car_price_predictor_pipeline"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Documentation complète: airflow/README_AIRFLOW.md"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
